# A NUMPY INTRODUCTION

Numpy is the basic library for all the numerical computations we need to do in Python in a faster way than a list.

In particular it has some very quick function to operate on the array created with this library, that we will see.


Let's start importing the library and seeing the version:

In [2]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

# 1. Why Numpy is so fast?

Let's remind that in Python an integer is built by four parts:

1. a reference to the memory allocation.
2. the type of the variable.
3. the syze of the data.
4. the integer value that we want that the Python variable represent.

It's very different from a C integer that is only a pointer to a memory region where it could be found the bytes that encode the integer value. All these informations that we have in Python are used to code freely and dynamically. 

But this has a cost.
In fact we can memorize a set of integer in a list as:

In [4]:
listInteger = [2, 3, 4, 5]
print(listInteger)
print(type(listInteger))

[2, 3, 4, 5]
<class 'list'>


The main problem of this list is that we memorize each information associated to each integer. But most of this information is redundant. In fact we know that all the data are integer so we don't need to memorize each time the same information. 

Numpy on the contrary fix the type of its arrays and add efficient operations on its elements knowing this structure. 

### 2. The Basics

Let's see how to create a numpy array from a list:

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


or a matrix, a 2-D dimensional array, from two lists:

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


To see the dimensions of our array we can use:

In [6]:
a.ndim

1

In [7]:
b.shape

(2, 3)

We can also see the type of the variable in the array

In [32]:
a.dtype

dtype('int32')

And also the number of bytes:

In [29]:
a.nbytes

12

and the number opf elements in the array:

In [8]:
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

Let's now see how to access to the element of a numpy array.

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


To get a specific element in position <code>[r, c]</code>

In [10]:
a[1, 5]

13

Or to get a specific row, for example the first one:

In [15]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

And to get a specific column:

In [16]:
a[:, 2]

array([ 3, 10])

But sometime we need to jump some step so we can use the slicing with this rule: <code>[startindex:endindex:stepsize]</code>.

In [12]:
a[0, 1:-1:2]

array([2, 4, 6])

To modify some elements:

In [24]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


Previously we have seen only 2-d example but we can create something different, a 3-d example. This tensor dimensionality is very useful in deep learning.

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


We can use the same dimensions as before:

In [17]:
b[0,1,1]

4

In [21]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [22]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### 2.1 Initializing Different Types of Arrays

We can now use some of the numpy function, for example to create some different types of arrays.

Zero matrix:

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

One matrix:

In [26]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

Matrix full of some number:

In [44]:
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

Or using random numbers:

In [27]:
np.random.rand(4,2)

array([[0.9137604 , 0.67985163],
       [0.14999802, 0.9218947 ],
       [0.6507209 , 0.67679086],
       [0.52366779, 0.20598582]])

And we can explicit the size:

In [73]:
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

Or use the identity matrix:

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

We can also repeat several times an array:

In [82]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Let's do some operation using what we have done:

In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Pay attention to the copy by reference:

In [28]:
a = np.array([1,2,3])
b = a.copy()
c = a 
b[0] = 100

print(a)
print(b)
c[0] = 2
print(a)

[1 2 3]
[100   2   3]
[2 2 3]


### 2.3 Basic Mathematics

Let's now pass to do some mathematical operations.

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [33]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### 2.4 Linear Algebra

In [36]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

For matrix multiplication:

In [37]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

For determinant:

In [38]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### 2.5 Statistics and other data science operation

In [39]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

We can search the mind of the array in the whole one:

In [40]:
np.min(stats)

1

Or we can search the max only by row:

In [41]:
np.max(stats, axis=1)

array([3, 6])

or by column:

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

or we can do the mean:

In [42]:
np.mean(stats)

3.5

### 2.6 Reorganizing Arrays 

Sometimes it can be useful to reshape an array:

In [44]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])